// Statik şehir/bölge listesi — src/db/locations/geojsons verisinden üretilmiştir (name + number).
// Public API bu küçük listeyi kullanır; 21MB geojson verisi yalnızca internal serviste yüklenir.
module.exports = [
	{ name: 'Kıbrıs', number: 82 },
	{ name: 'Adriyatik Denizi', number: -1 },
	{ name: 'Feature', number: 355 },
	{ name: 'Azerbaycan', number: 994 },
	{ name: 'Bosna Hersek', number: 387 },
	{ name: 'Bulgaristan', number: 359 },
	{ name: 'Ermenistan', number: 374 },
	{ name: 'Filistin', number: 970 },
	{ name: 'Gürcistan', number: 995 },
	{ name: 'Hırvatistan', number: 385 },
	{ name: 'Irak', number: 964 },
	{ name: 'İran', number: 98 },
	{ name: 'İsrail', number: 972 },
	{ name: 'Libya', number: 218 },
	{ name: 'Lübnan', number: 961 },
	{ name: 'Makedonya', number: 389 },
	{ name: 'Mısır', number: 20 },
	{ name: 'Montenegro', number: 382 },
	{ name: 'Rusya', number: 7 },
	{ name: 'Sırbistan', number: 381 },
	{ name: 'Suriye', number: 963 },
	{ name: 'Ürdün', number: 962 },
	{ name: 'Yunanistan', number: 30 },
	{ name: 'Akdeniz Açıkları (Suriye)', number: -1 },
	{ name: 'Akdeniz Açıkları (Türkiye)', number: -1 },
	{ name: 'Akdeniz Açıkları (Türkiye - Yunanistan)', number: -1 },
	{ name: 'Marmara Denizi', number: -1 },
	{ name: 'Kıbrıs Açıkları', number: -1 },
	{ name: 'Karadeniz', number: -1 },
	{ name: 'Ege Denizi', number: -1 },
	{ name: 'Adana', number: 1 },
	{ name: 'Adıyaman', number: 2 },
	{ name: 'Afyon', number: 3 },
	{ name: 'Ağrı', number: 4 },
	{ name: 'Aksaray', number: 68 },
	{ name: 'Amasya', number: 5 },
	{ name: 'Ankara', number: 6 },
	{ name: 'Antalya', number: 7 },
	{ name: 'Ardahan', number: 75 },
	{ name: 'Artvin', number: 8 },
	{ name: 'Aydın', number: 9 },
	{ name: 'Balıkesir', number: 10 },
	{ name: 'Bartın', number: 74 },
	{ name: 'Batman', number: 72 },
	{ name: 'Bayburt', number: 69 },
	{ name: 'Bilecik', number: 11 },
	{ name: 'Bingöl', number: 12 },
	{ name: 'Bitlis', number: 13 },
	{ name: 'Bolu', number: 14 },
	{ name: 'Burdur', number: 15 },
	{ name: 'Bursa', number: 16 },
	{ name: 'Çanakkale', number: 17 },
	{ name: 'Çankırı', number: 18 },
	{ name: 'Çorum', number: 19 },
	{ name: 'Denizli', number: 20 },
	{ name: 'Diyarbakır', number: 21 },
	{ name: 'Düzce', number: 81 },
	{ name: 'Edirne', number: 22 },
	{ name: 'Elazığ', number: 23 },
	{ name: 'Erzincan', number: 24 },
	{ name: 'Erzurum', number: 25 },
	{ name: 'Eskişehir', number: 26 },
	{ name: 'Gaziantep', number: 27 },
	{ name: 'Giresun', number: 28 },
	{ name: 'Gümüşhane', number: 29 },
	{ name: 'Hakkari', number: 30 },
	{ name: 'Hatay', number: 31 },
	{ name: 'Iğdır', number: 76 },
	{ name: 'Isparta', number: 32 },
	{ name: 'İstanbul', number: 34 },
	{ name: 'İzmir', number: 35 },
	{ name: 'Kahramanmaraş', number: 46 },
	{ name: 'Karabük', number: 78 },
	{ name: 'Karaman', number: 70 },
	{ name: 'Kars', number: 36 },
	{ name: 'Kastamonu', number: 37 },
	{ name: 'Kayseri', number: 38 },
	{ name: 'Kilis', number: 79 },
	{ name: 'Kırıkkale', number: 71 },
	{ name: 'Kırklareli', number: 39 },
	{ name: 'Kırşehir', number: 40 },
	{ name: 'Kocaeli', number: 41 },
	{ name: 'Konya', number: 42 },
	{ name: 'Kütahya', number: 43 },
	{ name: 'Malatya', number: 44 },
	{ name: 'Manisa', number: 45 },
	{ name: 'Mardin', number: 47 },
	{ name: 'Mersin', number: 33 },
	{ name: 'Muğla', number: 48 },
	{ name: 'Muş', number: 49 },
	{ name: 'Nevşehir', number: 50 },
	{ name: 'Niğde', number: 51 },
	{ name: 'Ordu', number: 52 },
	{ name: 'Osmaniye', number: 80 },
	{ name: 'Rize', number: 53 },
	{ name: 'Sakarya', number: 54 },
	{ name: 'Samsun', number: 55 },
	{ name: 'Şanlıurfa', number: 63 },
	{ name: 'Siirt', number: 56 },
	{ name: 'Sinop', number: 57 },
	{ name: 'Şırnak', number: 73 },
	{ name: 'Sivas', number: 58 },
	{ name: 'Tekirdağ', number: 59 },
	{ name: 'Tokat', number: 60 },
	{ name: 'Trabzon', number: 61 },
	{ name: 'Tunceli', number: 62 },
	{ name: 'Uşak', number: 64 },
	{ name: 'Van', number: 65 },
	{ name: 'Yalova', number: 77 },
	{ name: 'Yozgat', number: 66 },
	{ name: 'Zonguldak', number: 67 },
];
